#define ONESHOT_TAP_TOGGLE 1
#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_16BIT
#define COMBO_COUNT 10
#define RGB_MATRIX_STARTUP_SPD 60
#define RGBLIGHT_EFFECT_BREATHING
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define TAPPING_TOGGLE 2